### ISSUE TITLE
Kuro

### ISSUE THREAD

**Issue by dmproia** [ProjektKuro/kuro-api#12]
This creation of kuro as an api is code from another who authored the original code with an MIT. The IDs being used are from his certificate. Would you mind sharing how such code was obtained?

**Comment by tlahmann** [comment]
Hey @dmproia i'm not sure if I understood the question correctly. Could you elaborate on which IDs you mean?

**Comment by dmproia** [comment]
Source code api id = mine from my server. It’s not just you but a handful of people here on github have a ton of my code and it links to my stuff.

**Comment by tlahmann** [comment]
I still don't quite get what ID you're referring to. Could you tell me where I could find and or verify this? 

The code was initially a clone from [gothinkster/node-express-realworld-example-app](https://github.com/gothinkster/node-express-realworld-example-app) which itself is unlicensed. The [parent repository](https://github.com/gothinkster/realworld) (refering to these examples) is licesed with the MIT license as is this repository.

**Comment by vytas7** [comment]
Hello! Just heads up.
IMHO this looks like a spam bot, cf https://github.com/falconry/falcon/issues/1725 & https://github.com/falconry/falcon/issues/1726

**Comment by SvenPatrickMeier** [comment]
We also had a look at his profile and found the issue @dmproia opened in your project. 
I would agree with you thinking that this is spam. Therefore the conversation will be locked and the issue will be closed now.
